name: CI
on: [push]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1

      - name: Install dependencies
        run: |
          pip list
          poetry install --no-interaction

      - name: Run tests
        run: |
          poetry run pytest
